name: rick_and_morty
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.0-24.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  http: ^1.5.0
  bloc_concurrency: ^0.3.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.0
  shared_preferences: ^2.5.3
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    git:
      url: https://github.com/flutter/flutter.git
      path: packages/integration_test
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
